services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    expose:
      - 9091
    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SERVER=${EMAIL_SERVER}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=${AUTHELIA_JWT_PASSWORD}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      # Only uncomment HMAC secret if you plan to use OIDC
      # - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=${AUTHELIA_OIDC_HMAC_SECRET}
      # Example Client Credentials using OIDC
      # - N8N_CLIENT_ID=${N8N_CLIENT_ID}
      # - N8N_CLIENT_SECRET_HASH=${N8N_CLIENT_SECRET_HASH}
    volumes:
      - .:/config
      - ./logs:/var/log/authelia
    networks:
      - crowdsec
      - default
      - diun
      - traefik
    labels:
      - "crowdsec.enable=true"
      - "crowdsec.labels.type=authelia"
      - "diun.enable=true"
      - "homepage.group=Security"
      - "homepage.name=Authelia"
      - "homepage.icon=authelia.png"
      - "homepage.href=https://auth.${DOMAIN}"
      - "homepage.description=Authentication"
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)"
      - "traefik.http.routers.authelia.tls=true"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.routers.authelia.middlewares=chain-no-auth@file"
    security_opt:
      - no-new-privileges:true
