api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
    network: traefik
  file:
    filename: /config.yml
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_SSL_EMAIL}
      storage: /etc/traefik/acme.json
      tlsChallenge: {}

log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"
  format: json
accessLog: {}
  # filePath: "/var/log/traefik/access.log"
  # format: json
