services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    ports:
      - 9080:8080
    environment:
      - DOCKER_HOST=tcp://socket-proxy:2375
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true # Removes old images after update
      - "WATCHTOWER_SCHEDULE=0 18 * * *" # Updates at 6 PM daily
      - WATCHTOWER_LABEL_ENABLE=true # Updates only labeled containers
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_KEY}
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${EMAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
    networks:
      - homepage
      - socket-proxy
      - watchtower
    depends_on:
      - socket-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Maintenance"
      - "homepage.name=Watchtower"
      - "homepage.icon=watchtower.png"
      - "homepage.description=Automatic container updates"
      - "homepage.widget.type=watchtower"
      - "homepage.widget.url=http://watchtower:8080"
      - "homepage.widget.key=${WATCHTOWER_API_KEY}"
    security_opt:
      - no-new-privileges:true
