services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest # Use portainer-ee if you have a Business Edition license key
    command: -H tcp://socket-proxy:2375 # Docker Socket Proxy
    restart: unless-stopped
    ports:
      - 9100:9000
    environment:
      - TZ=${TZ}
    volumes:
      - portainer_data:/data
    networks:
      - homepage
      - socket-proxy
      - traefik
      - watchtower
    depends_on:
      - socket-proxy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "homepage.group=Maintenance"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer.png"
      - "homepage.href=https://portainer.${DOMAIN}/"
      - "homepage.description=Container management"
      - "homepage.widget.type=portainer"
      - "homepage.widget.url=http://portainer:9000"
      - "homepage.widget.env=1"
      - "homepage.widget.key=${PORTAINER_API_KEY}"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer.middlewares=chain-secure-ip@file"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    security_opt:
      - no-new-privileges:true

volumes:
  portainer_data:
